project:
  type: website
  execute-dir: project
  resources: [
    shinydataset,
    scripts
  ]

website:
  title: "MA 415 Final Project Group 6"
  navbar:
    right:
      - about.qmd
      - big_picture.qmd
      - analysis.qmd
      - data.qmd
format:
  html:
    theme: cosmo
    css: styles.css



