---
title: Data
description: We describe the sources of our data and the cleaning process.
toc: true
draft: false
---


This dataset is from the 2023 SURVEY and DOCUMENTATION of Behavioral Risk Factor Surveillance System in CDC’s website, which can be found on https://www.cdc.gov/brfss/annual_data/annual_2023.html.  The data was collected by the Centers for Disease Control and Prevention (CDC) in partnership with state health departments and U.S. territories.  Through phone interviews, the data tracks trends in behaviors, diseases, and conditions that pose significant risks to health over time and identifies different health outcomes across populations. 


## Relevant Variables:
The data file is called the Behavioral Risk Factor Surveillance System (BRFSS) and we intended to explore the variables from each categorization.
* Identity-Based: For variables that describe the identity of respondents and detailed information related to their race, gender, age, and veteran status just to name a few: “RACE”  corresponds to a respondent’s race, “Gender” to their gender, “_AGE_G” to their age category , “State” to the state they reside in, “EDUCA” to their education status,  and “VETERAN3” to their veteran status.

* *Insurance Status* : Variables Detailing Insurance Status include  “PRIMINS1” which has been renamed to “insurace_status”, and “MEDCOST1” which details times when respondents couldn’t afford to seek professional help.
Economic and Financial: This category of  variables includes computed income categories like “ _INCOMG1” , “MSCODE”  which describes the metropolitan status, “EMPLOY1” which describes the employment status of the respondent
Income:  INCOME3

* *The Health Category* :  includes variables that contain information regarding mental health and variables with information describing the physical well-being of respondents.

* *Variables for Physical health include* :  “PHYSHLTH” which accounts the number of days respondents are physically unwell.  “CHECKUP1”  details the time since the last routine checkup. “GENHLTH” renamed “Health Status”  describes the general health status of an individual.
“POORHLTH” describes the number of days in the past 30 days that an individual's physical health was not good, “BMI5CAT”  contains the respondent’s body mass index, renamed “BMI category”. The Life Habits section also provides some background into a respondent’s physical health, we look at variables like  “EXEROFT1” that measures exercise frequency, “EXERHMM1” that measures the amount of time spent exercising, and “_PAINDX3” that meansures the Physical Activity Index.

* *Variables for Mental Health* : “SDLONELY” which indicates how often respondents feel lonely, “SDHSTRE1” which indicates how often respondents feel stressed, “LSATISFY” which quantifies a respondent’s satisfaction with their life, “EMTSUPRT” which describes how often respondents  get the social and emotional support they need, and “MENHLTH” which describes the number of days respondents are mentally unwell.


* *Contributing Factors* : Such as Adverse Childhood Experiences & Social Determinants

The Social Determinants  and Health Equity section contains the variable” FOODSTMP”  that details if respondents receive food-stamps (SNAP) during the past 12 months. We also look at many variables that detail adverse childhood experiences, such as respondents living with people who expressed mentally unhealthy behaviors and abused substances. There are additional variables that track if respondents experienced emotional or physical abuse in their childhood. We also are interested in looking at variables that describe the current chronic health conditions of respondents(diabetes, COPD, heart disease, stroke), as well as variables that track their substance use patterns. Such as “ALCDAY4” which tracks alcohol consumption and “DIABETE4” which indicates if a respondent has diabetes. This section of variables provides insight into factors that  contribute to the respondents current health status.


## Cleaning Methodology
Regardless of the types of variables, the dataset reports everything using numerical values. For example, “99” may represent the respondent refusing to answer. Therefore, we renamed and recoded many of the variables to make our data clearer in [cleaning script](/scripts/load_and_clean_data.R). In addition, we also combined variables that are describing the same thing. For example, we combined the number of times respondents did exercise 1(that they spent the most time doing) and exercise 2 (that they spent the second most time doing) per month. 
```{r}
source(
  "scripts/load_and_clean_data.R",
  echo = FALSE 
)

brfss_clean|>
  select(RACE, State,Health_status, Exercise_frequency, insurance_status)|>
  head(5)
```


We have filtered the missing values in our major variables to ensure the first regression model we are going to do will not be influenced by those. We removed the NA values from the combined variable “Exercise_frequency” and found that most of the NA values have been removed. One additional R package named “haven”  is also used except tidyverse and dyplyr for reading the original dataset in XPT format. 

We have cleaned and transformed the dataset to make it more readable and suitable for analysis. By converting numeric codes into human-readable labels (e.g., health status, race, emotional support) and filtering out incomplete records, the code prepares a dataset that is easier to interpret and analyze, facilitating further analysis and visualization.

----

## Rubric: On this page

You will

* Describe where/how to find data.
  * You must include a link to the original data source(s). Make sure to provide attribution to those who collected the data.
  * Why was the data collected/curated? Who put it together? (This is important, if you don't know why it was collected then that might not be a good dataset to look at.
* Describe the different data files used and what each variable means. 
  * If you have many variables then only describe the most relevant ones and summarize the rest.
* Describe any cleaning you had to do for your data.
  * You *must* include a link to your `load_and_clean_data.R` file.
  * Rrename variables and recode factors to make data more clear.
  * Also, describe any additional R packages you used outside of those covered in class.
  * Describe and show code for how you combined multiple data files and any cleaning that was necessary for that.
  * Some repetition of what you do in your `load_and_clean_data.R` file is fine and encouraged if it helps explain what you did.
* Organization, clarity, cleanliness of the page
  * Make sure to remove excessive warnings, use clean easy-to-read code (without side scrolling), organize with sections, use bullets and other organization tools, etc.
  * This page should be self-contained.