---
title: "Blog Post 5"
author: ""
date: "2024-11-11"
date-modified: "2024-11-11"
draft: FALSE
---

[Link for the new joining dataset](https://apps.bea.gov/iTable/?reqid=70&step=1&isuri=1&acrdn=9&_gl=1*1lwyymi*_ga*NDgzMzEzNzcxLjE3MzEzNjY1MTQ.*_ga_J4698JNNFT*MTczMTM2NjUxMy4xLjEuMTczMTM2Njg1OC4xNS4wLjA.#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCI2MDAiXSxbIk1ham9yX0FyZWEiLCIwIl0sWyJTdGF0ZSIsWyIwIl1dLFsiQXJlYSIsWyJYWCJdXSxbIlN0YXRpc3RpYyIsWyItMSJdXSxbIlVuaXRfb2ZfbWVhc3VyZSIsIkxldmVscyJdLFsiWWVhciIsWyIyMDIzIl1dLFsiWWVhckJlZ2luIiwiLTEiXSxbIlllYXJfRW5kIiwiLTEiXV19)



**New Dataset**

Our dataset  is called regional Data: GDP and Personal Income. This dataset is the economic summary statistics for all the States in the U.S. in 2023, which includes personal income, GDP, consumer spending, price indexes, and employment. This dataset is available on Bureau of Economic Analysis, U.S. Department of Commerce.

 We intend to join the dataset at the state level to look at trends across states for economic factors. Although we haven't joined our datasets, we have multiple exploratory questions that connect both datasets and have identified possible trends we can look for.
 
The dataset addresses income statuses and disparities across states, we’d like to compare the health statuses across states. Do states with higher income have better income, how is it affecting the quality of life mentally and physically? Are unhealthy behaviors related to income statuses, are high employment related to decreases in substance use? Do areas with higher minority populations vary in wealth? We can look at the price index, does it correlate with having health insurance?

After joining the dataset we will start to investigate our exploratory questions and hopefully create visualizations to better understand the relationships.
