---
title: "Blog Post 6"
author: ""
date: "2024-11-17"
date-modified: "2024-11-17"
draft: FALSE
---

We successfully combined our two datasets on the “state” variable that was present in both datasets, this resulted in a dataset that provided a more comprehensive financial perspective on the factors we are currently looking at. Some of the data analytic questions we explored in the new dataset include:  Whether state income is correlated with physical health status, the relationship between state gdp on overall loneliness level, the relationship between alcohol use and state employment quantity, the relationship between Insurance Status, per capita current dollar statistics for each state, and if there is a correlation BMI category and alcohol consumption.


Statistical models we implemented in our analysis include logistic modeling, which was used to examine the state gdp levels affect the overall tendency to feel lonely. The results were statistically significant, showing that richer states actually correlates with a higher tendency of loneliness. With a 10-fold increase in state GDP, the likelihood of the residents of that state feeling lonely increases by about 8.1%. We also included the factor variable called Age Group, and the model shows that higher age individuals are less likely to experience loneliness when compared to the 18-24 individuals.
```{r example1}
source(
  "scripts/load_and_clean_data.R",
  echo = FALSE 
)

loneliness <- merged_data|>
  filter(loneliness_feeling_frequency == "Always" | loneliness_feeling_frequency == "Usually" |
           loneliness_feeling_frequency == "Rarely" | loneliness_feeling_frequency == "Never")|>
  mutate(Binary_lonely = if_else(loneliness_feeling_frequency %in% c("Always", "Usually"), 1, 0))|>
  select(`Gross domestic product (GDP)`, AGE_GROUP, Binary_lonely, EDUCA, `Personal income`)

mod1 <- glm(
  Binary_lonely ~  log10(`Gross domestic product (GDP)`)+ as.factor(AGE_GROUP),
  data = loneliness,
  family = "binomial"
)
  
summary(mod1)
```


Another tool we used is a correlation test to examine whether a correlation exists between state income and physical health status. The result is very close to 0, which shows that there is little to no linear relationship between these two variables. 


We also used box plots to plot the relationship between insurance status and per capita dollar statistics per state. In determining the relationship between BMI category and average alcohol drink per day, we use the box plot with the binomial regression model, but the outcome shows a really weak positive relationship between them. We also explored the relationship between the number of alcoholic drinks and the number of employment across different states using a scatter plot with a fitted line to show the relationship. However, there is a very weak positive correlation between the number of alcoholic drinks and the number of state employment quantities.


We want to continue this exploratory analysis in the future with an interest to see how those economic or insurance factors are correlated with socially related or behavioral variables across different races to see the race disparities.
