---
title: "Blog Post 1"
author: "Cindy Frempong, Zhenyi Yuan, Yueyi Wang, Qizheng Yang, Turley Duque"
date: "2024-10-11"
date-modified: "2024-10-11"
draft: FALSE
---

**Data Set 1:**

Original Link: https://www.ciesin.columbia.edu/data/sepher/ 

About Dataset: This Dataset hopes to reveal information about the impacts of climate change on vulnerable populations.

Number of rows and columns: 1664 columns and 86457 rows


The dataset  was created by merging multiple publicly available datasets that include socio-economic, climate risk scores, evictions and housing variables, along with census information for the US. Datasets merged include  the CDC vulnerability index dataset, FEMA’s  national risk index dataset, and Evictions and Home mortgage data. The Home Mortgage Dataset  is managed by the Consumer Financial Protection Bureau . The Evictions dataset is compiled and managed by the Eviction Lab at Princeton University.  We also would utilize US census tract data in addition to this dataset. We can load the data and it comes cleaned, but we can clean it further to meet our requirements and needs. 

A theme we want to address is how climate change incidents are impacting different demographics, from a racial and economic standpoint. At what frequency are people being displaced, who are the majority of people being displaced? What are their economic, social, and demographic backgrounds? This is especially relevant because we are currently seeing more extreme natural disasters globally and domestically, this would further inform about  the communities that are at the brunt  of such disasters. Some challenges we might encounter are challenges that often come with manipulating large datasets. When working with a huge mass of data that has numerous variables it can be difficult to come up with an extremely specific research question, also multiple variables can impact the other and correlate with each other although we might only be assessing a few. Being that the data is so detailed we have to be careful in our analysis when describing variables as correlated or not.



**Data Set 2**

Original Link: https://www.cdc.gov/brfss/annual_data/annual_2023.html

This data set ranges over 48 states, the District of Columbia, Guam, Puerto Rico, and the US Virgin Islands in 2023. It includes self-reported health behaviors (including mental health), chronic health conditions, and use of preventive services survey for 433,323 observations. There are 350 variables detailing characteristics such as race, geography, education levels, marital status, and gender. The data was collected through phone interviews to track trends in behaviors, diseases, and conditions that pose significant risks to health over time and identify different health outcomes across populations. 

By analyzing this data set, we hope to answer questions like how prevalent certain health risk behaviors are across populations, health disparities, and some variables (such as dietary habits or preventative services) that have a significant impact on the health outcomes. We can also look at mental health and find out groups that are most susceptible to mental health disorders. The data set has a clear codebook to it, but we can do some additional cleaning to make it meet our needs. Some challenges we foresee are that because this is a big data set with 350 variables, we may need to clearly select variables that correlate with our questions. 



**Data Set 3**

Original Link:https://docs.google.com/spreadsheets/d/1ce06FnS7lX0ilbEjnTmdj71t_UwnbR7fK4BkGO4k25I/edit?usp=sharing


This data set is extracted from NLSY79 Cohort, which is a longitudinal project that follows the lives of a sample of American youth born between 1957-64. The cohort originally included 12,686 respondents ages 14-22 when first interviewed in 1979; after two subsamples were dropped, 9,964 respondents remain in the eligible samples. We only extracted data from the year 2020 and focused on healthcare information, such as coverage, health conditions, and income.
There are 29 columns and 12,686 rows. 
The immediate challenge we can forsee is that this dataset has many missing data that need to be cleaned, and every variable is labeled by number, which needs further coding to make it more readable.
Although it seems challenging to do, I will be able to clean the data.
Also, we need to brainstorm what possible information/correlation are interesting and could be pulled out. 
The potential question: what is the portion with health issues that are covered by a medicare


It includes variables:
ASSESSMENT OF R'S GENERAL HEALTH

HOW MUCH SLEEP R GETS AT NIGHT ON WEEKDAYS-HOURS

SAMPLE IDENTIFICATION CODE

R'S RACIAL/ETHNIC COHORT FROM SCREENER

SEX OF R

IN THE PAST MONTH, DID R SUFFER FROM CHRONIC PAIN FROM AN ILLNESS OR MEDICAL CONDITION?

IN THE PAST MONTH, HOW OFTEN DID R SUFFER FROM CHRONIC PAIN FROM AN
ILLNESS OR MEDICAL CONDITION?

ANYONE IN R'S HOUSEHOLD BESIDES R DISABLED OR CHRONICALLY ILL?

R HAVE HEALTH CARE PROVIDER TO SEE WHEN SICK OR NEED HEALTH ADVICE?

R COVERED BY ANY HEALTH/HOSPITALIZATION 

SOURCE OF HEALTH/HOSPITALIZATION(RESPONDENT) - PRIVATE INSURANCE

R'S CURRENT/PREVIOUS EMPLOYER

R COVERED BY MEDICAID

HOW LONG SINCE R LAST HAD HEALTH CARE COVERAGE

REASONS R NOT HAVING HEALTH INSURANCE - PERSON WITH INSURANCE LOST
JOB OR CHANGED EMPLOYERS

REASONS R NOT HAVING HEALTH INSURANCE(7 variables about reasons)

SPOUSE COVERED BY ANY HEALTH/HOSPITALIZATION PLAN

TOTAL INCOME FROM WAGES AND SALARY IN PAST CALENDAR YEAR 

R MISSED PAYMENT OR BEEN AT LEAST 2 MONTHS LATE SINCE DATE OF LAST
INTERVIEW?

FAMILY POVERTY STATUS IN PREVIOUS CALENDAR YEAR

